baseURL = "https://getcloudnative.io/"
languageCode = "en-us"
title = "GCn - GetCloudnative"

[menu]
  [[menu.main]]
    identifier = "about us"
    name = "About Us"
    url = "https://www.linkedin.com/company/getcloudnative"
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://medium.com/getcloudnative"
    
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projecs/"

  [[menu.socials]]
    identifier = "github"
    name = "GitHub"
    pre = '<svg width="21" height="16"><path d="M15.33 0c.28.62.45 1.64.19 2.39 1.08.91 1.45 3.14.93 4.96 1.54.12 3.37-.06 4.55.41-1.1-.14-2.62-.42-4.04-.32-.27.02-.67-.01-.65.37 1.65.13 3.29.27 4.64.69-1.34-.22-2.97-.55-4.64-.6-.7 1.35-2.08 2.02-4 2.16.2.44.6.61.7 1.33.14 1.07-.23 2.64.14 3.35.17.35.46.35.65.65-.47.55-1.63-.07-1.77-.65-.22-1 .35-2.54-.27-3.21.04 1.08-.26 2.61.04 3.58.12.38.47.53.37.87-2.18.22-1.27-2.8-1.62-4.59-.33.02-.19.5-.19.69 0 1.74.36 4.14-1.53 3.9-.06-.36.25-.49.37-.82.34-.98-.07-2.45.1-3.63-.73.54.07 2.43-.38 3.4-.26.55-1.09.8-1.72.55.08-.42.52-.35.7-.74.25-.54 0-1.31.1-2.1-1.35.26-2.38-.05-2.89-.88-.23-.38-.28-.82-.56-1.15-.27-.33-.7-.38-.83-.83 1.65-.4 1.72 1.7 3.2 1.75.46.02.7-.13 1.12-.23.12-.53.37-.92.74-1.2-1.85-.25-3.38-.82-4.09-2.2-1.68.08-3.22.3-4.64.64a15.4 15.4 0 0 1 4.6-.69c-.1-.6-.99-.43-1.54-.4-1.02.04-2.3.16-3.11.31 1.17-.41 2.82-.36 4.41-.37-.48-1.51-.31-3.92.75-4.82-.3-.75-.21-1.98.18-2.57C6.53.05 7.24.57 8 1.06 8.91.8 9.9.66 11.15.74c.53.02 1.09.26 1.49.22.39-.03.82-.47 1.2-.64.5-.22.92-.3 1.5-.32z" /></svg>'
    url = "https://github.com/getcloudnative"

  [[menu.socials]]
    identifier = "linkedin"
    name = "LinkedIn"
    pre = '<svg width="16" height="16"><path d="M8.87 7.5v-.34l-.22.34h.22z"/><path d="M0 0v16h16V0H0zm4.98 13.3H2.6V6.14h2.38v7.14zM3.79 5.17h-.02c-.8 0-1.3-.55-1.3-1.24 0-.7.52-1.23 1.34-1.23.8 0 1.3.53 1.32 1.23 0 .69-.51 1.24-1.34 1.24zm9.75 8.11h-2.38V9.47c0-.96-.34-1.61-1.2-1.61-.65 0-1.04.44-1.22.87-.06.15-.08.36-.08.57v4H6.3s.03-6.48 0-7.15h2.37v1.01c.32-.48.88-1.18 2.14-1.18 1.57 0 2.74 1.02 2.74 3.22v4.1z" /></svg>'
    url = "https://www.linkedin.com/company/getcloudnative"
  
  [[menu.socials]]
    identifier = "speakerdeck"
    name = "Speaker Deck"
    pre = '<svg width="26" height="16"><path d="M10.6932331,10 L5,10 C2.23857624,10 0,7.76142376 0,5 C0,2.23857624 2.23857624,0 5,0 L11.6421053,0 C12.7466748,0 13.6421053,0.89543048 13.6421053,2 C13.6421053,3.10456952 12.7466748,4 11.6421053,4 L4.8977444,4 C4.3454596,4 3.8977444,4.44771528 3.8977444,5 C3.8977444,5.55228472 4.3454596,6 4.8977444,6 L10.5909774,6 C13.3524012,6 15.5909774,8.23857624 15.5909774,11 C15.5909774,13.7614238 13.3524012,16 10.5909774,16 L2,16 C0.89543048,16 0,15.1045695 0,14 C0,12.8954305 0.89543048,12 2,12 L10.6932331,12 C11.2455178,12 11.6932331,11.5522847 11.6932331,11 C11.6932331,10.4477153 11.2455178,10 10.6932331,10 Z M14.9013633,16 C16.231303,15.1005667 17.1818454,13.666797 17.4567639,12 L20.6843433,12 C21.2273117,12 21.6674746,11.5522847 21.6674746,11 L21.6674746,5 C21.6674746,4.44771528 21.2273117,4 20.6843433,4 L14.8210526,4 C15.2880793,3.46924352 15.5720602,2.7683544 15.5720602,2 C15.5720602,1.2316456 15.2880793,0.53075648 14.8210526,0 L21.6674746,0 C23.8393484,0 25.6,1.79086104 25.6,4 L25.6,12 C25.6,14.209139 23.8393484,16 21.6674746,16 L14.9013633,16 Z" /></svg>'
    url = "https://speakerdeck.com/getcloudnative"
  
  [[menu.socials]]
    identifier = "twitter"
    name = "Twitter"
    pre = '<svg width="18" height="15"><path d="M18 1.77c-.66.3-1.37.51-2.12.6A3.79 3.79 0 0 0 17.5.27c-.71.44-1.5.76-2.34.93a3.64 3.64 0 0 0-2.7-1.2 3.74 3.74 0 0 0-3.6 4.65A10.4 10.4 0 0 1 1.26.69 3.83 3.83 0 0 0 2.4 5.75c-.6-.02-1.18-.2-1.68-.48v.05A3.77 3.77 0 0 0 3.7 9.04a3.65 3.65 0 0 1-1.67.06 3.7 3.7 0 0 0 3.45 2.63A7.29 7.29 0 0 1 0 13.3 10.25 10.25 0 0 0 5.66 15c6.8 0 10.5-5.77 10.5-10.78v-.49A7.48 7.48 0 0 0 18 1.77z" /></svg>'
    url = "https://twitter.com/getcloudn8tv"
  
  [[menu.legal]]
    identifier = "Imprint"
    name = "Imprint"
    url = "/imprint/"

  [[menu.privacy]]
    identifier = "Privacy"
    name = "Privacy"
    url = ""

[params]
  description = "At GetCloudnative, we personally help our clients in bringing new and better products and services to the market quicker, by combining modern, cloud-native technology with Agile and Lean thinking and acting. We're Strategists, hands-on Executors, and Enablers of Teams. Ready to kick-start innovation and walk the talk together?"
  keywords = "Strategy, Architecture, Execution, Enablement, Agile, Lean, Agile Coaching, Continuous Delivery, DevOps, Cloud, Containers, Serverless, Amazon Web Services, AWS, Ansible, Azure, Docker, Jenkins, Kubernetes, OpenShift, Packer, Terraform"

  [[params.testimonials]]
    quotee = "Chris Morgan"
    position = "Director, Cloud Platforms Technical Marketing"
    company = "Redhat"
    image = "/chris-morgan.jpg"
    logo = "/redhat-logo.svg"
    quote = "While I was at Red Hat and Martin was at Dynatrace, I had the good fortune to work with him as a partner for close to 3 years. During that time, Martin's responsiveness, attention to detail, technical and business awareness of the partnership details helped to revive and expand the work between our two companies. Regardless of the situation, I knew that Martin would be able to offer insight and guidance to move things forward."
  
  [[params.testimonials]]
    quotee = "Peter Putz"
    position = "Operations Lead at Innovation Lab"
    company = "Dynatrace"
    image = "/peter-putz.jpg"
    logo = "/dynatrace-logo.svg"
    quote = "While working as a Senior Technology Strategist with the Dynatrace Innovation Lab Martin distinguished himself as a technical visionary and business strategist. As an outstanding expert in CI/CD and cloud technologies, he was at the forefront of scouting, assessing and adopting rapidly emerging technologies to advance the Dynatrace industry-leading monitoring solution. He was key in establishing strategic alliances with global cloud providers and successfully lead go-to-market efforts by bringing together cross-functional and globally distributed teams. His diligence and keen sense of technological advancements made him a well-respected player within the cloud community."
  
  [[params.testimonials]]
    quotee = "Günter Schramm"
    position = "Director Technical Customer Support"
    company = "Dynatrace"
    image = "/guenter-schramm.jpg"
    logo = "/dynatrace-logo.svg"
    quote = "I had the pleasure to work with Martin during his time at Dynatrace. My team regularly consulted with him on business-relevant cloud-native and microservices technology, such as Red Hat OpenShift and Kubernetes. Together with Martin, we've developed a training program to help our globally distributed teams embrace these emerging technologies -- and knowing how much professionalism Martin puts into his work, it comes as no surprise to me that his training concepts and material have remained in high demand ever since. Martin has this rare ability to understand complex technology in all its depth, and explain it to others in a simple and understandable way. It's that combination that makes him an extraordinary enabler and technology evangelist."